### ISSUE TITLE
Ajustar sidebar

### ISSUE THREAD

**Issue by fdaciuk** [wpbrasil/odin-expo#14]
A sidebar ficou um pouco "grande" (na altura), no meu notebook (1366x768px): 

![selection_133](https://cloud.githubusercontent.com/assets/487669/8585817/b4a575ca-25bd-11e5-8cc4-af213b385ddf.png)

Talvez diminuir um pouco o logo, ou mudar o formato da sidebar, sei lá. Sugestões?

cc. @wpbrasil/developers

**Comment by adammacias** [comment]
Tirar esse `<hr>` entre os links "Enviar um site" e "RSS".

\- ou - 

Adicionar um scrollbar vertical quando necessário.
