### ISSUE TITLE
Grupo Valdir Saraiva

### ISSUE THREAD

**Issue by chrdesigner** [wpbrasil/odin-expo#22]
Sistema desenvolvido para o Grupo Valdir Saraiva, junto com mais 8 hotsites sendo um deles uma loja virtual com base em WooCommerce.

http://grupovaldirsaraiva.com.br/

![grupovaldirsaraiva](https://cloud.githubusercontent.com/assets/5238941/14230143/8d9e493c-f922-11e5-8207-a491acdf2c73.png)

**Comment by chrdesigner** [comment]
Algum informação esta incorreta? qualquer coisa eu posso arrumar...

**Comment by adammacias** [comment]
@chrdesigner manda PR :) [como enviar](http://expo.wpod.in/about/#como-enviar-um-site)

Anexo imagem otimizada e com corte correto.

![8d516euybj6kcaaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/1139893/15088504/5f0c38ae-13cb-11e6-9d10-7af0c4388fbd.png)

**Comment by chrdesigner** [comment]
Muito obrigado...
