### ISSUE TITLE
14 BIS DIGITAL

### ISSUE THREAD

**Issue by leonardop21** [wpbrasil/odin-expo#27]
Site desenvolvido para a empresa 14 Bis Digital

http://www.14bisdigital.com.br/

![screenshot](https://cloud.githubusercontent.com/assets/17708447/24773944/738027c6-1aed-11e7-895a-6788fb4f971f.png)

**Comment by adammacias** [comment]
@leonardop21 a imagem deve ter dimensões 1000x800px, em 90% de zoom.

Tambem é recomendado otimizar a imagem através de um otimizador como o [TinyPNG](https://tinypng.com/) 😃

**Comment by leonardop21** [comment]
Agora sim @adammacias dimensões 1000x800px e otimizado no TinyPng :smiley: 

![14bisdigital](https://cloud.githubusercontent.com/assets/17708447/24864958/2de4d9d6-1ddc-11e7-97db-89d76a2a77e3.png)
