### ISSUE TITLE
Domínio

### ISSUE THREAD

**Issue by fdaciuk** [wpbrasil/odin-expo#7]
@claudiosmweb vc tem acesso ao domínio http://wpod.in né? Poderíamos criar um subdomínio pra esse cara aqui, o que acha? xD

Depois só precisa criar um link pra ele no site do Odin :smile:

**Comment by RafaelFunchal** [comment]
Eu pensei em inserir o link do showcase no site do Odin, mas ainda bem que não o fiz. A ideia do subdomínio foi muito boa, @fdaciuk.

**Comment by fdaciuk** [comment]
Pois é @rafaelfunchal! Dae é só criar um CNAME aqui e boa :dancer:

**Comment by fdaciuk** [comment]
Mas não tem problema inserir esse link lá. Depois, com o CNAME, o Github faz o redirect ;)

**Comment by claudiosanches** [comment]
Me fale qual subdominio que já configuro na DO

**Comment by fdaciuk** [comment]
Eu pensei em `expo.wpod.in`. 

O que acham?

**Comment by valeriosouza** [comment]
Gostei @fdaciuk

**Comment by adammacias** [comment]
:+1: Curti a ideia do domínio! 

@rafaelfunchal e sua sugestão é boa mesmo assim, é legal ter um link no menu do site Odin apontando para esse sub-domínio sugerido! :dancer: 

Na vdd já até [tem essa linha](https://github.com/wpbrasil/odin/blob/gh-pages/index.html#L41) dos cases, só que esta comentada porque não não tinha o expo :kissing:

**Comment by claudiosanches** [comment]
Eu acho que eu fiz certo aqui xD
Testem ai até meia noite

**Comment by fdaciuk** [comment]
Já deu! Atualizado! :dancer: :dancer: :sparkles:

**Comment by fdaciuk** [comment]
Só descomentar a linha do case e colocar o link lá no site do Odin agora @adammacias :smile:

**Comment by fdaciuk** [comment]
Atualizei lá :D

**Comment by claudiosanches** [comment]
Eu tinha criado o A record e não tinha certeza que estava certo ou não xD
Olha ai, tem SysAdmin que eu conheço que fala que isso assim é trabalho de 2 dias :p

**Comment by fdaciuk** [comment]
hauehaeuaehaue :stuck_out_tongue_winking_eye:

**Comment by RafaelFunchal** [comment]
>  tem SysAdmin que eu conheço que fala que isso assim é trabalho de 2 dias

LOL
